# -*- coding: utf-8 -*-
"""CustomerSegmentation_K-Means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DyoAGv1mDKWvAQfaNwH8UFDqueQdtDu

# **Customer Segmentation using K-Means Project**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""# **Loading Data set**"""

df=pd.read_csv('https://raw.githubusercontent.com/aved991/customer_segmentation---Unsupervised-Machine-Learning/refs/heads/main/data%20set/Mall_Customers(K-Means%20algo).csv')
df

df.rename(columns={'Annual Income (k$)':'Annual_Income(k$)'}, inplace=True)
df

